### PR TITLE
add option to disable account creation if no mapped roles or default role

### LINKED ISSUE #51: Auto create account with "none" as default role should deny access to unmapped users
As I understand when I read the config page in "If there is no default role, the user will not be able to log in with Shibboleth.", unmapped roles should deny access when default role is set to "None". But it's not the case : an account is still created with no role and the user is logged in, which can be a security issue in some structures, like ours.

To solve this, I temporarily edited the code in the function shibboleth_create_new_user, moving "$user_role = shibboleth_get_user_role();" from line 636 to line 617 and adding " || empty( $user_role )" to the condition at line 619.

Is it possible to implement a fix in the next release ? I actually use the latest version (2.1.1).

### PR DESCRIPTION
**Pull request by dandalpiaz**

### CODE REVIEW

**Review by jrchamp — APPROVED** [review]
This looks really good to me. I want to know your thoughts on adding underscores to the noaccount role to indicate that it's a reserved word, like `_no_account`. I'm not sure if I prefer with or without the extra literal spaces around the inline `selected()`, nor how I would alter the "Do NOT" language to make it less loud.

**Comment by dandalpiaz** [comment]
Added a new commit to change the "noaccount" name to "_no_account"; I think that's better. I also made an update to the `selected()` function to follow the formatting shown at the bottom of this reference page, https://developer.wordpress.org/reference/functions/selected/. 

I agree, the "Do NOT" label is pretty harsh sounding - definitely open to other label names. "Prevent account creation"? Or maybe add "(none)" to the label as well to give it juxtaposition to the existing "(none)", e.g. "(none) - prevent account creation". Any other ideas?

I'm pretty new to plugin development, so I appreciate all the feedback!

**Comment by jrchamp** [comment]
Comparing this to the existing "(none)", I think the parentheses imbues special meaning. As far as meaning, choosing this option will mean that:

- when a user does not have an account
- and that user does not have a non-default role mapping
- and the default role mapping is _no_account
- then do not create an account for them

Conversely as positives:

- when a new user needs an account
- and that user's role mapping is _no_account
- then skip account creation

Perhaps "(skip 'no role' account creation)" or "(none) and skip '(none)' account creation"? Part of me wants to rename the "(none)" item to "(no role)"...

Hopefully these ideas help somewhat. Ultimately, I think you're on the right track and whatever you decide is probably best. :+1: Thank you for your contributions on this @dandalpiaz !

**Review by jrchamp — APPROVED** [review]
This is easily the simplest solution I've seen to address #51 

Thank you @dandalpiaz for providing this.

**Comment by neverything** [comment]
Tested this pull request on a system I work with and it works as promised, thanks @dandalpiaz. I'll use this version starting next week up until a new release with this included is ready.

**Pull request merged**
